from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.sdk.drivers import webdriver
from subtests import test_set_cookies
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: ProdAutomationTests
    Package: TestProject.Generated.Tests.ProdAutomationTests
    Test: PublicReviewPageRenders_Prod
    Generated by: Marcel Bauer (marcel.bauer@surecritic.com)
    Generated on 02/04/2022, 17:32:29
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="pzPF3v1EcLh8hl2HU5DhzW96w2IKd1-zzl6paLZVTZg1",
                              project_name="ProdAutomationTests",
                              job_name="PublicReviewPageRenders_Prod")
    step_settings = StepSettings(timeout=45018)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """In_Production_This will click a dealer from the public SureCritic site and verify that the Review page renders."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://www.surecritic.com/"

    # 1. will navigate to the cookies page and save cookies
    # Set Cookies
    test_set_cookies.test_main(driver)

    # 2. Navigate to 'https://www.surecritic.com/reviews?utf8=%E2%9C%93&term=Korum+Hyundai&viewport=&gl%5Blat%5D=47.3784&gl%5Blng%5D=-122.217&gl%5Bprecision%5D=metro&gl%5Baccuracy%5D=&gl%5Bstreet_address%5D=&gl%5Bcity%5D=Kent&gl%5Bstate%5D=Washington&gl%5Bzip%5D=&gl%5Bfull_address%5D=Kent%2C+WA&near=Kent%2C+wa'
    # Search for Korum Hyundai
    driver.get("https://www.surecritic.com/reviews?utf8=%E2%9C%93&term=Korum+Hyundai&viewport=&gl%5Blat%5D=47.3784&gl%5Blng%5D=-122.217&gl%5Bprecision%5D=metro&gl%5Baccuracy%5D=&gl%5Bstreet_address%5D=&gl%5Bcity%5D=Kent&gl%5Bstate%5D=Washington&gl%5Bzip%5D=&gl%5Bfull_address%5D=Kent%2C+WA&near=Kent%2C+wa")

    # 3. Is 'business-summary-card-4688' visible?
    # Is Korum Hyundai Business Card Visible
    step_settings = StepSettings(timeout=35000)
    with DriverStepSettings(driver, step_settings):
        business_summary_card_4688 = driver.find_element(By.XPATH,
                                                         "//div[4]/div/div[1]/div[1]/div/div[2]/div/div[2]")
        assert business_summary_card_4688.is_displayed()

    # 4. Is 'DIV' present?
    # Is Map Loaded and visible
    step_settings = StepSettings(timeout=35000)
    with DriverStepSettings(driver, step_settings):
        div = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[1]/div/div/div/div[2]/div[2]")

    # 5. Click 'Korum Hyundai'
    # Click Korum Hyundai Heading
    korum_hyundai = driver.find_element(By.XPATH,
                                        "//div[2]/div[2]/div[2]//h2[. = '\nKorum Hyundai\n']")
    korum_hyundai.click()

    # 6. Is 'Business Solutions' visible?
    # Is Business Solutions Link Visible
    business_solutions = driver.find_element(By.XPATH,
                                             "//a[. = ' Business Solutions\n\n\n']")
    assert business_solutions.is_displayed()

    # 7. Click 'Click Business Solution Open'
    # Click Business Solution Open
    click_business_solution_open = driver.find_element(By.XPATH,
                                                       "//a/i[2]")
    click_business_solution_open.click()

    # 8. Click 'I1'
    # Click Business Solution Close
    i1 = driver.find_element(By.XPATH,
                             "//body/div[2]/div/a/i")
    i1.click()

    # 9. Is 'Business Image on BRP' visible?
    # BRP Business Image is Visible
    business_image_on_brp = driver.find_element(By.XPATH,
                                                "//div[5]/div/div[2]/div[1]/div/img")
    assert business_image_on_brp.is_displayed()

    # 10. Is 'Write a Review' visible?
    write_a_review = driver.find_element(By.XPATH,
                                         "//div[2]/a[. = 'Write a Review']")
    assert write_a_review.is_displayed()

    # 11. Is 'NPS Icon BRP' visible?
    # NPS Icon
    nps_icon_brp = driver.find_element(By.XPATH,
                                       "//div[2]/div[2]/div[1]/div[3]/div/div")
    assert nps_icon_brp.is_displayed()

    # 12. Is 'Schedule Appointment' visible?
    schedule_appointment = driver.find_element(By.XPATH,
                                               "//a[. = ' Schedule Appointment']")
    assert schedule_appointment.is_displayed()

    # 13. Is 'Star ratings on BRP' visible?
    # Star ratings on BRP
    star_ratings_on_brp = driver.find_element(By.XPATH,
                                              "//div[5]/div/div[2]/div[2]/div/div[2]")
    assert star_ratings_on_brp.is_displayed()

    # 14. Is 'Business Details on BRP' visible?
    # Business Details on BRP
    business_details_on_brp = driver.find_element(By.XPATH,
                                                  "//div[7]/div/div[1]/div/div[2]")
    assert business_details_on_brp.is_displayed()

    # 15. Is 'Business Hours' visible?
    business_hours = driver.find_element(By.XPATH,
                                         "//a[. = 'Business Hours']")
    assert business_hours.is_displayed()

    # 16. Is 'Get Directions' visible?
    get_directions = driver.find_element(By.XPATH,
                                         "//div[5]//a[. = 'Get Directions']")
    assert get_directions.is_displayed()

    # 17. Is 'Service Department' visible?
    service_department = driver.find_element(By.XPATH,
                                             "//div[6]//a[. = 'Service Department']")
    assert service_department.is_displayed()

    # 18. Is 'Sales Department' visible?
    sales_department = driver.find_element(By.XPATH,
                                           "//div[6]//a[. = 'Sales Department ']")
    assert sales_department.is_displayed()

    # 19. Is 'Certified Pre-Owned' visible?
    certified_pre_owned = driver.find_element(By.XPATH,
                                              "//div[6]//a[. = 'Certified Pre-Owned']")
    assert certified_pre_owned.is_displayed()

    # 20. Is 'Rescore Review Header' visible?
    # ReScore Reviews Renders
    step_settings = StepSettings(timeout=35000)
    with DriverStepSettings(driver, step_settings):
        rescore_review_header = driver.find_element(By.XPATH,
                                                    "//div[1]/div/div[1]/div[4]/h2")
        assert rescore_review_header.is_displayed()

    # 21. Is 'Service Department's Reviews' visible?
    service_department_s_reviews = driver.find_element(By.XPATH,
                                                       "//div[. = concat('Service Department', \"'\", 's Reviews')]")
    assert service_department_s_reviews.is_displayed()

    # 22. Is 'Review is Visible on BRP' visible?
    # Review is Visible on BRP
    review_is_visible_on_brp = driver.find_element(By.XPATH,
                                                   "//div/div/div[1]/div[3]/div/div[2]/div/div[1]/div[2]")
    assert review_is_visible_on_brp.is_displayed()

    # 23. Is 'Total rescores Icon BRP' visible?
    # Total rescores Icon BRP
    total_rescores_icon_brp = driver.find_element(By.XPATH,
                                                  "//div[1]/div/div[1]/div[6]/div[1]//i[2]")
    assert total_rescores_icon_brp.is_displayed()

    # 24. Is 'Rescores Average Icon BRP' visible?
    # Rescores Average Icon BRP
    rescores_average_icon_brp = driver.find_element(By.XPATH,
                                                    "//div[1]/div/div[1]/div[6]/div[2]//i[2]")
    assert rescores_average_icon_brp.is_displayed()

    # 25. Is 'NPS Icon (Score details section)' visible?
    # NPS Icon (Score details section)
    nps_icon_score_details_section_ = driver.find_element(By.XPATH,
                                                          "//div[1]/div/div[1]/div[6]/div[3]//i[2]")
    assert nps_icon_score_details_section_.is_displayed()

    # 26. Is 'Search Reviews' visible?
    search_reviews = driver.find_element(By.CSS_SELECTOR,
                                         "#review-search-field")
    assert search_reviews.is_displayed()

    # 27. Is 'Key Words Visible' visible?
    # Key Words Visible
    key_words_visible = driver.find_element(By.XPATH,
                                            "//div/div/div/div[1]/div[1]/div/div/div[2]/div/div/div[1]/a")
    assert key_words_visible.is_displayed()

    # 28. Is 'Write a Review Green Button' visible?
    # Write a Review Green Button
    write_a_review_green_button = driver.find_element(By.XPATH,
                                                      "//div[2]/div[1]/a[. = 'Write a Review']")
    assert write_a_review_green_button.is_displayed()

    # 29. Is 'Vehicles Reviews Section ' visible?
    # Vehicles Reviews Section
    vehicles_reviews_section_ = driver.find_element(By.XPATH,
                                                    "//div[8]/div/div/div[2]/div/div/div")
    assert vehicles_reviews_section_.is_displayed()

    # 30. Is 'Vehicle Card in Vehicle Review Section' visible?
    # Vehicle Card in Vehicle Review Section
    vehicle_card_in_vehicle_review_section = driver.find_element(By.XPATH,
                                                                 "//div[8]/div/div/div[2]/div/div/div/div[2]/div/div[1]")
    assert vehicle_card_in_vehicle_review_section.is_displayed()

    # 31. Is 'Pagination Check' visible?
    # Pagination Check is Visible
    pagination_check = driver.find_element(By.XPATH,
                                           "//a[. = '2']")
    assert pagination_check.is_displayed()

    # 32. Is 'The following reviews are either pend...' visible?
    # The following reviews are either pend...
    the_following_reviews_are_either_pend_ = driver.find_element(By.XPATH,
                                                                 "//a[. = 'The following reviews are either pending verification, not currently recommended, or have been flagged for violation of our Review Policy.']")
    assert the_following_reviews_are_either_pend_.is_displayed()

    # 33. Is 'Net Promoter® NPS®, NPS Prism®, and t...' visible?
    # NPS Terms Visible
    net_promoter_nps_nps_prism_and_t_ = driver.find_element(By.XPATH,
                                                            "//div[. = '\nNet Promoter® NPS®, NPS Prism®, and the NPS-related emoticons are registered trademarks of Bain & Company, Inc., Satmetrix Systems, Inc., and Fred Reichheld. Net Promoter Score™ and Net Promoter System™ are service marks of Bain & Company, Inc., and Fred Reichheld.\n']")
    assert net_promoter_nps_nps_prism_and_t_.is_displayed()

    # 34. Is 'SureCritic Inc 2010-
    # 2021' visible?
    surecritic_inc_2010_2021 = driver.find_element(By.XPATH,
                                                   "//div[. = '\n SureCritic Inc 2010-\n2021\n']")
    assert surecritic_inc_2010_2021.is_displayed()

    # 35. Is 'Privacy Policy' visible?
    privacy_policy = driver.find_element(By.XPATH,
                                         "//a[. = 'Privacy Policy']")
    assert privacy_policy.is_displayed()

    # 36. Is 'Terms of Use' visible?
    terms_of_use = driver.find_element(By.XPATH,
                                       "//a[. = 'Terms of Use']")
    assert terms_of_use.is_displayed()

    # 37. Is 'Review Policy' visible?
    review_policy = driver.find_element(By.XPATH,
                                        "//a[. = 'Review Policy']")
    assert review_policy.is_displayed()

    # 38. Is 'facebook Icon' visible?
    # facebook Icon
    facebook_icon = driver.find_element(By.XPATH,
                                        "//a[1]/div/i[2]")
    assert facebook_icon.is_displayed()

    # 39. Is 'LinkedIn Icon' visible?
    # LinkedIn Icon
    linkedin_icon = driver.find_element(By.XPATH,
                                        "//a[2]//i[2]")
    assert linkedin_icon.is_displayed()

    # 40. Is 'Twitter Icon' visible?
    # Twitter Icon
    twitter_icon = driver.find_element(By.XPATH,
                                       "//a[3]//i[2]")
    assert twitter_icon.is_displayed()

    # 41. Scroll window by ('0','5702')
    driver.execute_script("window.scrollBy(0,5702)")

    # 42. Is 'Floating Header' visible?
    # Floating Header
    floating_header = driver.find_element(By.XPATH,
                                          "//body/div[4]/div/div")
    assert floating_header.is_displayed()

    # 43. Navigate to 'https://www.surecritic.com/hyundai-dealer'
    # go to hyundai-dealer link
    driver.get("https://www.surecritic.com/hyundai-dealer")

    # 44. Is 'Hyundai Dealers in' visible?
    hyundai_dealers_in = driver.find_element(By.XPATH,
                                             "//div[2]/form//label[. = 'Hyundai Dealers in']")
    assert hyundai_dealers_in.is_displayed()

    # 45. Is 'business-summary-card-4694' visible?
    business_summary_card_4694 = driver.find_element(By.XPATH,
                                                     "//div[2]/div[6]")
    assert business_summary_card_4694.is_displayed()

    # 46. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 47. Is 'DIV1' visible?
    # Is Business Solutions and Sign In Visible
    div1 = driver.find_element(By.XPATH,
                               "//body/div[1]/div/div[2]")
    assert div1.is_displayed()
