from selenium.webdriver.common.by import By
from src.testproject.decorator import report_assertion_errors


"""
This pytest test was automatically generated by TestProject
    Project: ProdAutomationTests
    Package: TestProject.Generated.Tests.ProdAutomationTests
    Test: Set Cookies
    Generated by: Marcel Bauer (marcel.bauer@surecritic.com)
    Generated on 02/04/2022, 17:29:41
"""


@report_assertion_errors
def test_main(driver):
    """will navigate to the cookies page and save cookies."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://www.surecritic.com"

    # 1. Navigate to 'https://www.surecritic.com/cookies'
    # Navigates to the cookies page
    driver.get("https://www.surecritic.com/cookies")

    # 2. Click 'save Cookies Button'
    # Click save cookies
    save_cookies_button = driver.find_element(By.CSS_SELECTOR,
                                              "[name='commit']")
    save_cookies_button.click()
