from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
from subtests import test_set_cookies
from subtests import test_set_location
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: ProdAutomationTests
    Package: TestProject.Generated.Tests.ProdAutomationTests
    Test: New_PV3 HP Link Val - 3
    Generated by: Marcel Bauer (marcel.bauer@surecritic.com)
    Generated on 02/04/2022, 17:30:07
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="pzPF3v1EcLh8hl2HU5DhzW96w2IKd1-zzl6paLZVTZg1",
                              project_name="ProdAutomationTests",
                              job_name="New_PV3 HP Link Val - 3")
    step_settings = StepSettings(timeout=65018,
                                 sleep_time=1000,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Tests for all home page links are working and route correctly."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://www.surecritic.com"

    # 1. will navigate to the cookies page and save cookies
    test_set_cookies.test_main(driver)

    # 2. Navigate to 'https://www.surecritic.com/reviews'
    # Business reviews Link
    driver.get("https://www.surecritic.com/reviews")

    # 3. will set location to Kent, WA for Public V3 Tests
    test_set_location.test_main(driver)

    # 4. Is 'Businesses near Kent, WA' visible?
    businesses_near_kent_wa = driver.find_element(By.XPATH,
                                                  "//h1[. = 'Businesses near Kent, WA']")
    assert businesses_near_kent_wa.is_displayed()

    # 5. Navigate to 'https://www.surecritic.com/vehicles/reviews/makes'
    # Vehicle Reviews Link
    driver.get("https://www.surecritic.com/vehicles/reviews/makes")

    # 6. Is 'Browse All Vehicle Reviews' visible?
    # Vehicle Reviews Link
    browse_all_vehicle_reviews = driver.find_element(By.XPATH,
                                                     "//h1[. = 'Browse All Vehicle Reviews']")
    assert browse_all_vehicle_reviews.is_displayed()

    # 7. Navigate to 'https://www.surecritic.com/reviews?near=Kent%2C+WA&term=award+winning+import+auto+repair'
    # Award Winning Link
    driver.get(
        "https://www.surecritic.com/reviews?near=Kent%2C+WA&term=award+winning+import+auto+repair")

    # 8. Does 'term' contain 'award winning import auto repair'?
    # Validate search box contains "award winning import auto repair"
    term = driver.find_element(By.CSS_SELECTOR,
                               "#navbar_1-header-search-category-input")
    step_output = term.text
    assert step_output and ("award winning import auto repair" in step_output)

    # 9. Navigate to 'https://www.surecritic.com/reviews?near=Kent%2C+WA&term=affordable+transmission+repair'
    # Affordable Link
    driver.get(
        "https://www.surecritic.com/reviews?near=Kent%2C+WA&term=affordable+transmission+repair")

    # 10. Does 'term' contain 'affordable transmission repair'?
    # Validate search box contains "affordable transmission repair"
    term = driver.find_element(By.CSS_SELECTOR,
                               "#navbar_1-header-search-category-input")
    step_output = term.text
    assert step_output and ("affordable transmission repair" in step_output)

    # 11. Navigate to 'https://www.surecritic.com/reviews?near=Kent%2C+WA&term=recommended+rv+repair'
    # Recommended Link
    driver.get(
        "https://www.surecritic.com/reviews?near=Kent%2C+WA&term=recommended+rv+repair")

    # 12. Does 'term' contain 'recommended rv repair'?
    # Search Box contains "recommended rv repair"
    step_settings = StepSettings(timeout=35000)
    with DriverStepSettings(driver, step_settings):
        term = driver.find_element(By.CSS_SELECTOR,
                                   "#navbar_1-header-search-category-input")
        step_output = term.text
        assert step_output and ("recommended rv repair" in step_output)

    # 13. Navigate to 'https://www.surecritic.com/reviews?near=Kent%2C+WA&term=best+collision+repair'
    # Best Collision Link
    driver.get(
        "https://www.surecritic.com/reviews?near=Kent%2C+WA&term=best+collision+repair")

    # 14. Does 'term' contain 'best collision repair'?
    # Search box contains "best collision repair"
    term = driver.find_element(By.CSS_SELECTOR,
                               "#navbar_1-header-search-category-input")
    step_output = term.text
    assert step_output and ("best collision repair" in step_output)

    # 15. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 16. Is 'Find Reviews' visible?
    find_reviews = driver.find_element(By.XPATH,
                                       "//*[@id=\"homepage-search\"]/div/div/div[3]/button")
    assert find_reviews.is_displayed()

    # 17. Scroll window by ('0','3100')
    driver.execute_script("window.scrollBy(0,3100)")

    # 18. Is 'Award Winning Import Auto Repair1' visible?
    award_winning_import_auto_repair1 = driver.find_element(By.XPATH,
                                                            "//a[@href = '/reviews?near=Kent%2C+WA&term=award+winning+import+auto+repair']")
    assert award_winning_import_auto_repair1.is_displayed()

    # 19. Is 'Learn How' visible?
    learn_how = driver.find_element(By.XPATH,
                                    "//button[. = 'Learn How']")
    assert learn_how.is_displayed()

    # 20. Is 'Request a Demo' visible?
    request_a_demo = driver.find_element(By.XPATH,
                                         "//button[. = 'Request a Demo']")
    assert request_a_demo.is_displayed()

    # 21. Is 'Platform Overview1' visible?
    platform_overview1 = driver.find_element(By.XPATH,
                                             "//li[2]/a[@href = 'https://learn.surecritic.com/surecritic-for-business']")
    assert platform_overview1.is_displayed()

    # 22. Navigate to 'https://learn.surecritic.com/'
    # Learn How Link
    driver.get("https://learn.surecritic.com/")

    # 23. Is 'We're the pioneer of verified reviews' visible?
    # Learn How Link
    we_re_the_pioneer_of_verified_reviews = driver.find_element(By.XPATH,
                                                                "//strong[. = concat('We', \"'\", 're the pioneer of verified reviews')]")
    assert we_re_the_pioneer_of_verified_reviews.is_displayed()

    # 24. Is 'Get a Demo1' visible?
    # Learn How Link
    get_a_demo1 = driver.find_element(By.XPATH,
                                      "//div[2]/div[1]/div/div//a[. = '\n\t\t\t\t\t\t\tGet a Demo\n\t\t\t\t\t']")
    assert get_a_demo1.is_displayed()

    # 25. Is 'We're the pioneer of verified reviews' visible?
    # Learn How Link
    we_re_the_pioneer_of_verified_reviews = driver.find_element(By.XPATH,
                                                                "//strong[. = concat('We', \"'\", 're the pioneer of verified reviews')]")
    assert we_re_the_pioneer_of_verified_reviews.is_displayed()

    # 26. Navigate to 'https://learn.surecritic.com/surecritic-for-business/'
    # SC For Business Link
    step_settings = StepSettings(timeout=55018,
                                 sleep_time=1000,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        driver.get("https://learn.surecritic.com/surecritic-for-business/")

    # 27. Is 'SureCritic for Business App' visible?
    # SC For Business Link
    surecritic_for_business_app = driver.find_element(By.XPATH,
                                                      "//span[. = 'SureCritic for Business App']")
    assert surecritic_for_business_app.is_displayed()

    # 28. Navigate to 'https://learn.surecritic.com/reputation-monitoring/'
    # Reputation Monitoring Link
    step_settings = StepSettings(timeout=35000)
    with DriverStepSettings(driver, step_settings):
        driver.get("https://learn.surecritic.com/reputation-monitoring/")

    # 29. Is 'Reputation Monitoring1' visible?
    # Reputation Monitoring Link
    step_settings = StepSettings(timeout=35000)
    with DriverStepSettings(driver, step_settings):
        reputation_monitoring1 = driver.find_element(By.XPATH,
                                                     "//h1/span")
        assert reputation_monitoring1.is_displayed()

    # 30. Navigate to 'https://learn.surecritic.com/text-the-manager/'
    # text the manager link
    step_settings = StepSettings(timeout=55018,
                                 sleep_time=1000,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        driver.get("https://learn.surecritic.com/text-the-manager/")

    # 31. Is 'Text the Manager™1' visible?
    # text the manager link
    step_settings = StepSettings(timeout=35000)
    with DriverStepSettings(driver, step_settings):
        text_the_manager_1 = driver.find_element(By.XPATH,
                                                 "//h1/span")
        assert text_the_manager_1.is_displayed()

    # 32. Navigate to 'https://learn.surecritic.com/socialcsi/'
    # Social CSI Link
    driver.get("https://learn.surecritic.com/socialcsi/")

    # 33. Is 'colophon' visible?
    # Social CSI Link
    colophon = driver.find_element(By.CSS_SELECTOR,
                                   "#colophon")
    assert colophon.is_displayed()

    # 34. Navigate to 'https://learn.surecritic.com/cx-management/'
    # Customer Experience Link
    driver.get("https://learn.surecritic.com/cx-management/")

    # 35. Is 'Customer Experience (CX) Management1' visible?
    # Customer Experience Link
    customer_experience_cx_management1 = driver.find_element(By.XPATH,
                                                             "//span[. = 'Customer Experience (CX) Management']")
    assert customer_experience_cx_management1.is_displayed()

    # 36. Navigate to 'https://learn.surecritic.com/reviewreach'
    # review reach link
    step_settings = StepSettings(timeout=55018)
    with DriverStepSettings(driver, step_settings):
        driver.get("https://learn.surecritic.com/reviewreach")

    # 37. Is 'Get More Great Reviews in More Places' visible?
    # review reach link
    step_settings = StepSettings(timeout=35000)
    with DriverStepSettings(driver, step_settings):
        get_more_great_reviews_in_more_places = driver.find_element(By.XPATH,
                                                                    "//span[. = 'Get More Great Reviews in More Places']")
        assert get_more_great_reviews_in_more_places.is_displayed()

    # 38. Navigate to 'https://learn.surecritic.com/surecritic-for-business'
    # Surecritic for Business Link
    driver.get("https://learn.surecritic.com/surecritic-for-business")

    # 39. Is 'SureCritic for Business App' visible?
    # Surecritic for Business Link
    surecritic_for_business_app = driver.find_element(By.XPATH,
                                                      "//span[. = 'SureCritic for Business App']")
    assert surecritic_for_business_app.is_displayed()

    # 40. Navigate to 'https://www.surecritic.com/support'
    # Support link
    driver.get("https://www.surecritic.com/support")

    # 41. Is 'General Support1' visible?
    # Support link
    step_settings = StepSettings(timeout=35000)
    with DriverStepSettings(driver, step_settings):
        general_support1 = driver.find_element(By.XPATH,
                                               "//h1[. = 'General Support']")
        assert general_support1.is_displayed()

    # 42. Navigate to 'https://www.surecritic.com/faq'
    # FAQ Link
    driver.get("https://www.surecritic.com/faq")

    # 43. Is 'Frequently Asked Questions' visible?
    # FAQ Link
    frequently_asked_questions = driver.find_element(By.XPATH,
                                                     "//h1[. = 'Frequently Asked Questions']")
    assert frequently_asked_questions.is_displayed()
