from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.decorator import report_assertion_errors


"""
This pytest test was automatically generated by TestProject
    Project: ProdAutomationTests
    Package: TestProject.Generated.Tests.ProdAutomationTests
    Test: Set Location
    Generated by: Marcel Bauer (marcel.bauer@surecritic.com)
    Generated on 02/04/2022, 17:30:06
"""


@report_assertion_errors
def test_main(driver):
    """will set location to Kent, WA for Public V3 Tests."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://www.surecritic.com"

    # 1. Navigate to 'https://www.surecritic.com/reviews'
    # Navigates the specified URL (Auto-generated)
    driver.get("https://www.surecritic.com/reviews")

    # 2. Clear 'Clear Bus Location Text Box' contents
    # Clear Business Location text box
    clear_bus_location_text_box = driver.find_element(By.XPATH,
                                                      "//div[2]/form//input[@class = 'form-control right-spacer-xs header-search-location-input']")
    clear_bus_location_text_box.clear()

    # 3. Type 'Kent, WA' in 'near1'
    # Set location to Kent, WA
    near1 = driver.find_element(By.XPATH,
                                "//div[2]/form/div/input[12]")
    near1.send_keys("Kent, WA")

    # 4. Send 'ENTER' key(s)
    # hits enter button for Search
    ActionChains(driver).send_keys(Keys.ENTER).perform()
