from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.enums import TakeScreenshotConditionType
from src.testproject.sdk.drivers import webdriver
from subtests import test_set_cookies
from subtests import test_set_location
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: ProdAutomationTests
    Package: TestProject.Generated.Tests.ProdAutomationTests
    Test: PV3 Homepage Validations
    Generated by: Marcel Bauer (marcel.bauer@surecritic.com)
    Generated on 02/04/2022, 17:29:41
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="pzPF3v1EcLh8hl2HU5DhzW96w2IKd1-zzl6paLZVTZg1",
                              project_name="ProdAutomationTests",
                              job_name="PV3 Homepage Validations")
    step_settings = StepSettings(timeout=65018)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """This will verify the homepage Items appear as expected."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://www.surecritic.com"

    # 1. will navigate to the cookies page and save cookies
    # Set Cookies
    test_set_cookies.test_main(driver)

    # 2. will set location to Kent, WA for Public V3 Tests
    # Set Location to Kent, WA
    test_set_location.test_main(driver)

    # 3. Does 'Businesses near ' contain 'Businesses near '?
    # Validate Title contains Businesses near
    businesses_near_ = driver.find_element(By.XPATH,
                                           "//h1")
    step_output = businesses_near_.text
    assert step_output and ("Businesses near " in step_output)

    # 4. Is 'Homepage Top header' visible?
    homepage_top_header = driver.find_element(By.XPATH,
                                              "//body/div[1]")
    assert homepage_top_header.is_displayed()

    # 5. Is 'term' visible?
    term = driver.find_element(By.CSS_SELECTOR,
                               "#navbar_1-header-search-category-input")
    assert term.is_displayed()

    # 6. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    step_settings = StepSettings(
        screenshot_condition=TakeScreenshotConditionType.Always)
    with DriverStepSettings(driver, step_settings):
        driver.get(f'{ApplicationURL}')

    # 7. Is 'Homepage Top header' visible?
    # Home Page Header check
    step_settings = StepSettings(
        screenshot_condition=TakeScreenshotConditionType.Always)
    with DriverStepSettings(driver, step_settings):
        homepage_top_header = driver.find_element(By.XPATH,
                                                  "//body/div[1]")
        assert homepage_top_header.is_displayed()

    # 8. Is 'DIV8' visible?
    # Home Page Hero Image
    step_settings = StepSettings(timeout=35000)
    with DriverStepSettings(driver, step_settings):
        div8 = driver.find_element(By.XPATH,
                                   "//div[@class = 'image-overlay']")
        assert div8.is_displayed()

    # 9. Is 'Business Reviews' visible?
    # Check for Business Link in Header
    step_settings = StepSettings(timeout=35000)
    with DriverStepSettings(driver, step_settings):
        business_reviews = driver.find_element(By.XPATH,
                                               "//div[2]/a[. = 'Business Reviews']")
        assert business_reviews.is_displayed()

    # 10. Is 'Vehicle Reviews' visible?
    # Is Vehicle Reviews Link visible?
    step_settings = StepSettings(timeout=35000)
    with DriverStepSettings(driver, step_settings):
        vehicle_reviews = driver.find_element(By.XPATH,
                                              "//div[2]/a[. = 'Vehicle Reviews']")
        assert vehicle_reviews.is_displayed()

    # 11. Is 'Business Solutions Open' visible?
    # Is Bus Solutions Button Visible
    business_solutions_open = driver.find_element(By.XPATH,
                                                  "//a[. = ' Business Solutions\n\n\n']")
    assert business_solutions_open.is_displayed()

    # 12. Is 'Your Source for Verified Reviews' visible?
    # Check Your Source for Verified Reviews
    your_source_for_verified_reviews = driver.find_element(By.XPATH,
                                                           "//h1[. = 'Your Source for Verified Reviews']")
    assert your_source_for_verified_reviews.is_displayed()

    # 13. Is 'HomePage Search box' visible?
    homepage_search_box = driver.find_element(By.CSS_SELECTOR,
                                              "#term")
    assert homepage_search_box.is_displayed()

    # 14. Is 'near2' visible?
    # Home Page Location Text Box
    near2 = driver.find_element(By.CSS_SELECTOR,
                                "#near")
    assert near2.is_displayed()

    # 15. Is 'Find Reviews' visible?
    find_reviews = driver.find_element(By.XPATH,
                                       "//*[@id=\"homepage-search\"]/div/div/div[3]/button")
    assert find_reviews.is_displayed()

    # 16. Is 'Sign In' visible?
    sign_in = driver.find_element(By.XPATH,
                                  "//body/div[1]/div/div/a[2]")
    assert sign_in.is_displayed()

    # 17. Click 'Business Solutions Open'
    # Open Business Solutions
    business_solutions_open = driver.find_element(By.XPATH,
                                                  "//a[. = ' Business Solutions\n\n\n']")
    business_solutions_open.click()

    # 18. Click 'Close Business Solutions Close'
    # Close Business Solutions
    close_business_solutions_close = driver.find_element(By.XPATH,
                                                         "//div[2]/div/a/i")
    close_business_solutions_close.click()

    # 19. Is 'New Car Dealer' visible?
    # Is New Car Dealer Button visible?
    new_car_dealer = driver.find_element(By.XPATH,
                                         "//button[. = '\nNew Car Dealer\n']")
    assert new_car_dealer.is_displayed()

    # 20. Is 'Tire Sales and Repair' visible?
    tire_sales_and_repair = driver.find_element(By.XPATH,
                                                "//a[@href = '/tire-sales']")
    assert tire_sales_and_repair.is_displayed()

    # 21. Is 'Auto Repair' visible?
    # Auto Repair button
    auto_repair = driver.find_element(By.XPATH,
                                      "//a[@href = '/auto-repair']")
    assert auto_repair.is_displayed()

    # 22. Is 'Apartments' visible?
    # Apartments Button
    apartments = driver.find_element(By.XPATH,
                                     "//a[@href = '/apartments']")
    assert apartments.is_displayed()

    # 23. Is 'Body Shop' visible?
    # Body Shop Button
    body_shop = driver.find_element(By.XPATH,
                                    "//a[@href = '/body-shop']")
    assert body_shop.is_displayed()

    # 24. Is 'Featured Businesses Near Kent, WA' visible?
    featured_businesses_near_kent_wa = driver.find_element(By.XPATH,
                                                           "//section/h2")
    assert featured_businesses_near_kent_wa.is_displayed()

    # 25. Is 'featured-section' visible?
    featured_section = driver.find_element(By.CSS_SELECTOR,
                                           "#featured-section")
    assert featured_section.is_displayed()

    # 26. Is 'DIV9' visible?
    div9 = driver.find_element(By.XPATH,
                               "//section/div[3]/div/div/div[1]")
    assert div9.is_displayed()

    # 27. Is 'DIV10' visible?
    div10 = driver.find_element(By.XPATH,
                                "//section/div[3]/div/div/div[2]")
    assert div10.is_displayed()

    # 28. Is 'DIV11' visible?
    div11 = driver.find_element(By.XPATH,
                                "//section/div[3]/div/div/div[3]")
    assert div11.is_displayed()

    # 29. Is 'Show more Businesses Button' visible?
    show_more_businesses_button = driver.find_element(By.XPATH,
                                                      "//div[3]/div/div[2]//input")
    assert show_more_businesses_button.is_displayed()

    # 30. Is 'Your Experience Matters' visible?
    your_experience_matters = driver.find_element(By.XPATH,
                                                  "//h2[. = 'Your Experience Matters']")
    assert your_experience_matters.is_displayed()

    # 31. Is 'In a world of paid ads and endless sp...' visible?
    in_a_world_of_paid_ads_and_endless_sp_ = driver.find_element(By.XPATH,
                                                                 "//p[. = '\nIn a world of paid ads and endless spam, you deserve to see authentic experiences from real customers.\nSureCritic is your trusted, verified review platform where you can find businesses you rely on. SureCritic\ncollects diverse, unbiased feedback by asking all customers about their service. We want to hear from\neveryone, because your experience matters.\n']")
    assert in_a_world_of_paid_ads_and_endless_sp_.is_displayed()

    # 32. Is 'Marketing Image' visible?
    # Marketing Image
    marketing_image = driver.find_element(By.XPATH,
                                          "//section/div/div/div[1]/div[2]/div/img")
    assert marketing_image.is_displayed()

    # 33. Is 'Transparent binoculars' visible?
    transparent_binoculars = driver.find_element(By.XPATH,
                                                 "//section[2]/div/div/div[2]/div[1]/div/div[1]")
    assert transparent_binoculars.is_displayed()

    # 34. Is 'Transparent' visible?
    transparent = driver.find_element(By.XPATH,
                                      "//h2[. = 'Transparent']")
    assert transparent.is_displayed()

    # 35. Is 'All reviews play a part in your decis...' visible?
    all_reviews_play_a_part_in_your_decis_ = driver.find_element(By.XPATH,
                                                                 "//p[. = concat('\nAll reviews play a part in your decision-making process and we think it', \"'\", 's important you see all sides.\nReviews are never removed, so you get it all, the good, the bad, and the ugly.\n')]")
    assert all_reviews_play_a_part_in_your_decis_.is_displayed()

    # 36. Is 'ReScore Image' visible?
    # ReScore Image
    rescore_image = driver.find_element(By.XPATH,
                                        "//div[2]/div/div[1][. = '\n\n']")
    assert rescore_image.is_displayed()

    # 37. Is 'Rescore' visible?
    rescore = driver.find_element(By.XPATH,
                                  "//h2[. = 'Rescore']")
    assert rescore.is_displayed()

    # 38. Is 'Businesses hate when you walk away un...' visible?
    businesses_hate_when_you_walk_away_un_ = driver.find_element(By.XPATH,
                                                                 "//p[. = '\nBusinesses hate when you walk away unhappy. Our patented concern resolution technology, ReScore\nmotivates businesses to reach out and address any irritations after a bad experience.\n']")
    assert businesses_hate_when_you_walk_away_un_.is_displayed()

    # 39. Is 'Verified Image' visible?
    # Verified Image
    verified_image = driver.find_element(By.XPATH,
                                         "//section/div/div/div[2]/div[3]/div/div[1]")
    assert verified_image.is_displayed()

    # 40. Is 'Verified' visible?
    verified = driver.find_element(By.XPATH,
                                   "//h2[. = 'Verified']")
    assert verified.is_displayed()

    # 41. Is 'Review requests are sent from the bus...' visible?
    review_requests_are_sent_from_the_bus_ = driver.find_element(By.XPATH,
                                                                 "//p[. = concat('\nReview requests are sent from the business', \"'\", ' point-of-sale system to ensure each review is from an actual\ncustomer, not a bot. That way you know that each 5-star review is earned.\n')]")
    assert review_requests_are_sent_from_the_bus_.is_displayed()

    # 42. Is 'Recent Business Reviews Near You' visible?
    recent_business_reviews_near_you = driver.find_element(By.XPATH,
                                                           "//h2[. = 'Recent Business Reviews Near You']")
    assert recent_business_reviews_near_you.is_displayed()

    # 43. Is 'Latest Review Card Header 1' visible?
    # Latest Review Card Header
    latest_review_card_header_1 = driver.find_element(By.XPATH,
                                                      "//section[3]/div/div/div[1]/div[1]")
    assert latest_review_card_header_1.is_displayed()

    # 44. Is 'Latest Reviews Card Body 1' visible?
    latest_reviews_card_body_1 = driver.find_element(By.XPATH,
                                                     "//section[3]/div/div/div[1]/div[2]")
    assert latest_reviews_card_body_1.is_displayed()

    # 45. Is 'Latest Reviews Card Header 2' visible?
    # Latest Reviews Card Header 2
    latest_reviews_card_header_2 = driver.find_element(By.XPATH,
                                                       "//section[3]/div/div/div[2]/div[1]")
    assert latest_reviews_card_header_2.is_displayed()

    # 46. Is 'Latest Reviews Card Body 2' visible?
    # Latest Reviews Card Body 2
    latest_reviews_card_body_2 = driver.find_element(By.XPATH,
                                                     "//section[3]/div/div/div[2]/div[2]")
    assert latest_reviews_card_body_2.is_displayed()

    # 47. Is 'Latest Reviews Card Header 3' visible?
    # Latest Reviews Card Header 3
    latest_reviews_card_header_3 = driver.find_element(By.XPATH,
                                                       "//section/div/div/div[3]/div[1]")
    assert latest_reviews_card_header_3.is_displayed()

    # 48. Is 'Latest Reviews Card Body 3' visible?
    # Latest Reviews Card Body 3
    latest_reviews_card_body_3 = driver.find_element(By.XPATH,
                                                     "//section/div/div/div[3]/div[2]")
    assert latest_reviews_card_body_3.is_displayed()

    # 49. Is 'Latest Vehicle Reviews Card Header 1' visible?
    # Latest Vehicle Reviews Card Header 1
    latest_vehicle_reviews_card_header_1 = driver.find_element(By.XPATH,
                                                               "//div[3]/div[2]/div/div[1]/div[1]/div[1]")
    assert latest_vehicle_reviews_card_header_1.is_displayed()

    # 50. Is 'Latest Vehicle Reviews Vehicle Image 1' visible?
    # Latest Vehicle Reviews Vehicle Image 1
    latest_vehicle_reviews_vehicle_image_1 = driver.find_element(By.XPATH,
                                                                 "//div[2]/div/div[1]/div[1]/div[2]/img")
    assert latest_vehicle_reviews_vehicle_image_1.is_displayed()

    # 51. Is 'Latest Vehicle Reviews Vehicle Body 1' visible?
    # Latest Vehicle Reviews Vehicle Body 1
    latest_vehicle_reviews_vehicle_body_1 = driver.find_element(By.XPATH,
                                                                "//div[3]/div[2]/div/div[1]/div[1]/div[3]")
    assert latest_vehicle_reviews_vehicle_body_1.is_displayed()

    # 52. Is 'Latest Vehicle Reviews Vehicle Header 2' visible?
    # Latest Vehicle Reviews Vehicle Header 2
    latest_vehicle_reviews_vehicle_header_2 = driver.find_element(By.XPATH,
                                                                  "//div[3]/div[2]/div/div[1]/div[2]/div[1]")
    assert latest_vehicle_reviews_vehicle_header_2.is_displayed()

    # 53. Is 'Latest Vehicle Reviews Vehicle Image 2' visible?
    # Latest Vehicle Reviews Vehicle Image 2
    latest_vehicle_reviews_vehicle_image_2 = driver.find_element(By.XPATH,
                                                                 "//div[2]/div[2]/img")
    assert latest_vehicle_reviews_vehicle_image_2.is_displayed()

    # 54. Is 'Latest Vehicle Reviews Vehicle Body 2' visible?
    # Latest Vehicle Reviews Vehicle Body 2
    latest_vehicle_reviews_vehicle_body_2 = driver.find_element(By.XPATH,
                                                                "//div[3]/div[2]/div/div[1]/div[2]/div[3]")
    assert latest_vehicle_reviews_vehicle_body_2.is_displayed()

    # 55. Is 'See More Reviews Button ' visible?
    # See More Reviews Button
    see_more_reviews_button_ = driver.find_element(By.XPATH,
                                                   "//div[2]/div/div[2]//input")
    assert see_more_reviews_button_.is_displayed()

    # 56. Is 'Popular Searches Near Seattle' visible?
    popular_searches_near_seattle = driver.find_element(By.XPATH,
                                                        "//h2[. = 'Popular Searches Near Seattle']")
    assert popular_searches_near_seattle.is_displayed()

    # 57. Is 'Award Winning Import Auto Repair' visible?
    award_winning_import_auto_repair = driver.find_element(By.XPATH,
                                                           "//a[@href = '/reviews?near=Kent%2C+WA&term=award+winning+import+auto+repair']")
    assert award_winning_import_auto_repair.is_displayed()

    # 58. Is 'Affordable Transmission Repair' visible?
    affordable_transmission_repair = driver.find_element(By.XPATH,
                                                         "//a[@href = '/reviews?near=Kent%2C+WA&term=affordable+transmission+repair']")
    assert affordable_transmission_repair.is_displayed()

    # 59. Is 'Fastest Glass Repair' visible?
    fastest_glass_repair = driver.find_element(By.XPATH,
                                               "//a[. = 'Fastest Glass Repair']")
    assert fastest_glass_repair.is_displayed()

    # 60. Is 'Best Collision Repair' visible?
    best_collision_repair = driver.find_element(By.XPATH,
                                                "//a[. = 'Best Collision Repair']")
    assert best_collision_repair.is_displayed()

    # 61. Is 'Recommended RV Repair' visible?
    recommended_rv_repair = driver.find_element(By.XPATH,
                                                "//a[. = 'Recommended RV Repair']")
    assert recommended_rv_repair.is_displayed()

    # 62. Is 'Luxury European Auto Repair' visible?
    luxury_european_auto_repair = driver.find_element(By.XPATH,
                                                      "//div[. = 'Luxury European Auto Repair']")
    assert luxury_european_auto_repair.is_displayed()

    # 63. Is 'Best Body Shop' visible?
    best_body_shop = driver.find_element(By.XPATH,
                                         "//a[. = 'Best Body Shop']")
    assert best_body_shop.is_displayed()

    # 64. Is 'Premium Towing Service' visible?
    premium_towing_service = driver.find_element(By.XPATH,
                                                 "//a[. = 'Premium Towing Service']")
    assert premium_towing_service.is_displayed()

    # 65. Is 'explore-the-platform' visible?
    explore_the_platform = driver.find_element(By.CSS_SELECTOR,
                                               "#explore-the-platform")
    assert explore_the_platform.is_displayed()

    # 66. Is 'Build a Better Business' visible?
    build_a_better_business = driver.find_element(By.XPATH,
                                                  "//h2[. = 'Build a Better Business']")
    assert build_a_better_business.is_displayed()

    # 67. Is 'Collect valuable insight, foster bran...' visible?
    collect_valuable_insight_foster_bran_ = driver.find_element(By.XPATH,
                                                                "//p[. = '\nCollect valuable insight, foster brand trust, and improve customer experience so you can gain\nand maintain loyal customers.\n']")
    assert collect_valuable_insight_foster_bran_.is_displayed()

    # 68. Is 'Learn How' visible?
    learn_how = driver.find_element(By.XPATH,
                                    "//button[. = 'Learn How']")
    assert learn_how.is_displayed()

    # 69. Is 'Request a Demo' visible?
    request_a_demo = driver.find_element(By.XPATH,
                                         "//button[. = 'Request a Demo']")
    assert request_a_demo.is_displayed()

    # 70. Is 'Footer Container' visible?
    # Footer Container
    footer_container = driver.find_element(By.XPATH,
                                           "//footer/div[1]/div[1]")
    assert footer_container.is_displayed()

    # 71. Is 'Reviews1' visible?
    reviews1 = driver.find_element(By.XPATH,
                                   "//div[. = 'Reviews']")
    assert reviews1.is_displayed()

    # 72. Is 'Business Reviews1' visible?
    business_reviews1 = driver.find_element(By.XPATH,
                                            "//li[. = 'Business Reviews']")
    assert business_reviews1.is_displayed()

    # 73. Is 'Vehicle Reviews1' visible?
    vehicle_reviews1 = driver.find_element(By.XPATH,
                                           "//li[. = 'Vehicle Reviews']")
    assert vehicle_reviews1.is_displayed()

    # 74. Is 'For Business' visible?
    for_business = driver.find_element(By.XPATH,
                                       "//div[. = 'For Business']")
    assert for_business.is_displayed()

    # 75. Is 'Get a Demo' visible?
    get_a_demo = driver.find_element(By.XPATH,
                                     "//li/a[. = 'Get a Demo']")
    assert get_a_demo.is_displayed()

    # 76. Is 'Platform Overview' visible?
    platform_overview = driver.find_element(By.XPATH,
                                            "//li[. = 'Platform Overview']")
    assert platform_overview.is_displayed()

    # 77. Is 'Reputation Monitoring' visible?
    reputation_monitoring = driver.find_element(By.XPATH,
                                                "//li/a[@href = 'https://learn.surecritic.com/reputation-monitoring']")
    assert reputation_monitoring.is_displayed()

    # 78. Is 'Text the Manager™' visible?
    text_the_manager_ = driver.find_element(By.XPATH,
                                            "//div[2]/ul/li[4]/a")
    assert text_the_manager_.is_displayed()

    # 79. Is 'Social CSI™' visible?
    social_csi_ = driver.find_element(By.XPATH,
                                      "//li/a[@href = 'https://learn.surecritic.com/socialcsi']")
    assert social_csi_.is_displayed()

    # 80. Is 'Customer Experience Management' visible?
    customer_experience_management = driver.find_element(By.XPATH,
                                                         "//li/a[@href = 'https://learn.surecritic.com/cx-management']")
    assert customer_experience_management.is_displayed()

    # 81. Is 'ReviewReach™' visible?
    reviewreach_ = driver.find_element(By.XPATH,
                                       "//li[7]/a")
    assert reviewreach_.is_displayed()

    # 82. Is 'SureCritic for Business' visible?
    surecritic_for_business = driver.find_element(By.XPATH,
                                                  "//li[8]/a[@href = 'https://learn.surecritic.com/surecritic-for-business']")
    assert surecritic_for_business.is_displayed()

    # 83. Is 'Support' visible?
    support = driver.find_element(By.XPATH,
                                  "//div[. = 'Support']")
    assert support.is_displayed()

    # 84. Is 'General Support' visible?
    general_support = driver.find_element(By.XPATH,
                                          "//li/a[@href = '/support']")
    assert general_support.is_displayed()

    # 85. Is 'FAQ' visible?
    faq = driver.find_element(By.XPATH,
                              "//li[. = 'FAQ']")
    assert faq.is_displayed()

    # 86. Is 'Cookies' visible?
    cookies = driver.find_element(By.XPATH,
                                  "//li[. = 'Cookies']")
    assert cookies.is_displayed()

    # 87. Is 'About' visible?
    about = driver.find_element(By.XPATH,
                                "//div[. = 'About']")
    assert about.is_displayed()

    # 88. Is 'About SureCritic' visible?
    about_surecritic = driver.find_element(By.XPATH,
                                           "//li/a[. = 'About SureCritic']")
    assert about_surecritic.is_displayed()

    # 89. Is 'Blog' visible?
    blog = driver.find_element(By.XPATH,
                               "//li/a[@href = 'https://blog.surecritic.com']")
    assert blog.is_displayed()

    # 90. Is 'Careers' visible?
    careers = driver.find_element(By.XPATH,
                                  "//li/a[@href = 'https://learn.surecritic.com/careers']")
    assert careers.is_displayed()

    # 91. Is 'Contact Us' visible?
    contact_us = driver.find_element(By.XPATH,
                                     "//li/a[@href = '/contact']")
    assert contact_us.is_displayed()

    # 92. Is 'Home Page Footer' visible?
    # Home Page Footer
    home_page_footer = driver.find_element(By.XPATH,
                                           "//footer/div[2]")
    assert home_page_footer.is_displayed()

    # 93. Is 'SureCritic Inc 2010-
    # 2021' visible?
    surecritic_inc_2010_2021 = driver.find_element(By.XPATH,
                                                   "//div[. = '\n SureCritic Inc 2010-\n2021\n']")
    assert surecritic_inc_2010_2021.is_displayed()

    # 94. Is 'Privacy Policy' visible?
    privacy_policy = driver.find_element(By.XPATH,
                                         "//a[. = 'Privacy Policy']")
    assert privacy_policy.is_displayed()

    # 95. Is 'Terms of Use' visible?
    terms_of_use = driver.find_element(By.XPATH,
                                       "//a[. = 'Terms of Use']")
    assert terms_of_use.is_displayed()

    # 96. Is 'Review Policy' visible?
    review_policy = driver.find_element(By.XPATH,
                                        "//a[. = 'Review Policy']")
    assert review_policy.is_displayed()

    # 97. Is 'Facebook Icon' visible?
    # Facebook Icon
    facebook_icon = driver.find_element(By.XPATH,
                                        "//a[1]/div/i[2]")
    assert facebook_icon.is_displayed()

    # 98. Is 'LinkedIn Icon' visible?
    # LinkedIn Icon
    linkedin_icon = driver.find_element(By.XPATH,
                                        "//a[2]//i[2]")
    assert linkedin_icon.is_displayed()

    # 99. Is 'Twitter Icon' visible?
    # Twitter Icon
    twitter_icon = driver.find_element(By.XPATH,
                                       "//a[3]//i[2]")
    assert twitter_icon.is_displayed()

    # 100. Click 'Sign In'
    sign_in = driver.find_element(By.XPATH,
                                  "//body/div[1]/div/div/a[2]")
    sign_in.click()

    # 101. Is 'Sign In1' visible?
    sign_in1 = driver.find_element(By.XPATH,
                                   "//h1[. = 'Sign In']")
    assert sign_in1.is_displayed()

    # 102. Navigate to 'https://www.surecritic.com/reviews'
    # go to Business Reviews link
    driver.get("https://www.surecritic.com/reviews")

    # 103. Is 'near1' visible?
    near1 = driver.find_element(By.XPATH,
                                "//div[2]/form/div/input[12]")
    assert near1.is_displayed()

    # 104. Is 'Search' visible?
    search = driver.find_element(By.XPATH,
                                 "//div[2]/form/button[@type = 'submit']")
    assert search.is_displayed()

    # 105. Is 'Business Solutions Open' visible?
    business_solutions_open = driver.find_element(By.XPATH,
                                                  "//a[. = ' Business Solutions\n\n\n']")
    assert business_solutions_open.is_displayed()

    # 106. Click 'Business Solutions Open'
    # Open Bus Soluitions
    business_solutions_open = driver.find_element(By.XPATH,
                                                  "//a[. = ' Business Solutions\n\n\n']")
    business_solutions_open.click()

    # 107. Click 'Business Solutions Open'
    # Open Bus Soluitions
    business_solutions_open = driver.find_element(By.XPATH,
                                                  "//a[. = ' Business Solutions\n\n\n']")
    business_solutions_open.click()

    '''
    # (STEP DISABLED)
    # 108. Click 'Map view close business solutions'
    # Map view close business solutions
    map_view_close_business_solutions = driver.find_element(By.XPATH,
    "//div[3]/div/a/i")
    map_view_close_business_solutions.click()
    '''

    # 109. Is 'Sign in2' visible?
    # Map View Sign In button
    sign_in2 = driver.find_element(By.XPATH,
                                   "//a[. = 'Sign in']")
    assert sign_in2.is_displayed()

    # 110. Is 'DIV12' visible?
    # Business Search Map View
    step_settings = StepSettings(timeout=25000)
    with DriverStepSettings(driver, step_settings):
        div12 = driver.find_element(By.XPATH,
                                    "//*[@id=\"map-canvas\"]/div/div/div[2]/div[2]")
        assert div12.is_displayed()

    # 111. Is 'Search as I move Option on Map View' visible?
    # Search as I move Option on Map View
    search_as_i_move_option_on_map_view = driver.find_element(By.XPATH,
                                                              "//div[4]/div/div[1]/div[2]/div/div[3]/div/div[2]/div")
    assert search_as_i_move_option_on_map_view.is_displayed()

    # 112. Is 'Toggle fullscreen view' visible?
    toggle_fullscreen_view = driver.find_element(By.XPATH,
                                                 "//div/div[8]/button")
    assert toggle_fullscreen_view.is_displayed()

    # 113. Is 'Zoom in' visible?
    zoom_in = driver.find_element(By.XPATH,
                                  "//div[8]/div/div/div/button[1]")
    assert zoom_in.is_displayed()

    # 114. Is 'Zoom out' visible?
    zoom_out = driver.find_element(By.XPATH,
                                   "//div[8]/div//button[2]")
    assert zoom_out.is_displayed()

    # 115. Is 'business-summary-card-7086' visible?
    business_summary_card_7086 = driver.find_element(By.XPATH,
                                                     "//div[2]/div[5]")
    assert business_summary_card_7086.is_displayed()

    # 116. Is 'business-summary-card-66' visible?
    business_summary_card_66 = driver.find_element(By.XPATH,
                                                   "//div[2]/div[6]")
    assert business_summary_card_66.is_displayed()

    # 117. Is 'Auto Repair1' visible?
    auto_repair1 = driver.find_element(By.XPATH,
                                       "//button[. = '\n\nAuto Repair\n']")
    assert auto_repair1.is_displayed()

    # 118. Is 'Body Shop1' visible?
    body_shop1 = driver.find_element(By.XPATH,
                                     "//button[. = '\n\nBody Shop\n']")
    assert body_shop1.is_displayed()

    # 119. Is 'Car Maintenance' visible?
    car_maintenance = driver.find_element(By.XPATH,
                                          "//button[. = '\n\nCar Maintenance\n']")
    assert car_maintenance.is_displayed()

    # 120. Is 'Collision Repair' visible?
    collision_repair = driver.find_element(By.XPATH,
                                           "//button[. = '\n\nCollision Repair\n']")
    assert collision_repair.is_displayed()

    # 121. Is 'Business Cat Container Left Side' visible?
    business_cat_container_left_side = driver.find_element(By.XPATH,
                                                           "//body/div[4]/div/div[1]/div[1]/div/div[1]/div/div")
    assert business_cat_container_left_side.is_displayed()

    # 122. Click 'More Categories'
    step_settings = StepSettings(timeout=35000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        more_categories = driver.find_element(By.CSS_SELECTOR,
                                              "#moreCategoriesToggle")
        more_categories.click()

    # 123. Click 'Fewer Categories'
    fewer_categories = driver.find_element(By.CSS_SELECTOR,
                                           "#fewerCategoriesToggle")
    fewer_categories.click()

    # 124. Is 'Search for Business' visible?
    search_for_business = driver.find_element(By.XPATH,
                                              "//label[. = 'Search for Business']")
    assert search_for_business.is_displayed()

    # 125. Is 'Search for Business Text Box' visible?
    # Search for Business Text Box
    search_for_business_text_box = driver.find_element(By.CSS_SELECTOR,
                                                       "#term")
    assert search_for_business_text_box.is_displayed()

    # 126. Is 'Location' visible?
    location = driver.find_element(By.XPATH,
                                   "//label[. = 'Location']")
    assert location.is_displayed()

    # 127. Is 'Location text box' visible?
    # Location text box
    location_text_box = driver.find_element(By.CSS_SELECTOR,
                                            "#near")
    assert location_text_box.is_displayed()
